Improve authentication documentation
CakeDC/users pull request #1027
Opened 2023-02-09 19:05 UTC by ravage84

Various improvements

- Formatting
- Wording
- Grammar error
- Code, class name & path highlighing
- Namings
- De-emphasize less importaant remarks
- Update broken links

2023-02-09 19:06 UTC, ravage84 commented
@TerryKern can you have a look at this, please?

2023-02-10 10:20 UTC, rochamarcelo requested changes

2023-02-10 10:20 UTC, rochamarcelo commented on Docs/Documentation/Authentication.md
> +Fore xample, create a file ``src/Loader/AppAuthenticationServiceLoader.php``:
Typo in Fore xample.

2023-02-10 13:03 UTC, TerryKern approved these changes
Looks good to me

2023-02-10 13:23 UTC, rochamarcelo approved these changes

2023-02-10 13:23 UTC, merged

2023-02-10 13:23 UTC, rochamarcelo commented
Thank you.