Feature/account lockout policy
CakeDC/users pull request #1082
Opened 2024-03-28 18:38 UTC by rochamarcelo

Ref: https://github.com/CakeDC/users/issues/1081

2024-03-28 18:38 UTC, rochamarcelo commented
In progress

2024-03-29 11:14 UTC, steinkel requested changes
minor comment, OK to merge when fixed, thanks!

2024-03-29 11:14 UTC, steinkel commented on src/Identifier/PasswordLockout/LockoutHandler.php
> +        $attemptsCount = $this->getAttemptsCount($identity['id'], $timeWindow);
array key exists

2024-03-29 11:14 UTC, steinkel commented on src/Identifier/PasswordLockout/LockoutHandler.php
> +        $attemptsCount = $this->getAttemptsCount($identity['id'], $timeWindow);
please check similar items in this file too

2024-03-29 13:02 UTC, merged