fix login remember me with google authentication
CakeDC/users pull request #740
Opened 2018-12-12 20:11 UTC by arcmovex

I fixed the bug when I'm using google authenticator, the remember me cookie is not working thus the user session will be revoke even if the remember me is checked.

I used session based solution to pass the value without appearing in the url param.

Thanks.

2019-01-17 13:23 UTC, rochamarcelo requested changes

2019-01-17 13:23 UTC, rochamarcelo commented on src/Controller/Traits/LoginTrait.php
> +                    $this->request->data(Configure::read('Users.RememberMe.Cookie.name'), $hasRememberMe);
Please add a unit test for this

2019-01-17 13:23 UTC, rochamarcelo commented on src/Controller/Traits/LoginTrait.php
> +
Please fix code style issues https://travis-ci.org/CakeDC/users/jobs/467177140

2019-01-17 13:23 UTC, rochamarcelo commented on src/Controller/Traits/LoginTrait.php
> +                $hasRememberMe = $this->request->getSession()->read('hasRememberMe');
Please use a namespace key like Users.hasRememberMe

2019-01-17 13:23 UTC, rochamarcelo commented on src/Controller/Traits/LoginTrait.php
> +                    $this->request->getSession()->delete('hasRememberMe');
Please use a namespace key like Users.hasRememberMe

2019-01-17 13:23 UTC, rochamarcelo commented on src/Controller/Traits/LoginTrait.php
> +                    $this->request->getSession()->write('hasRememberMe', $this->request->getData(Configure::read('Users.RememberMe.Cookie.name')));
Please add an unit test for this

2019-04-06 17:14 UTC, Ali1 commented
Will do in a month

2025-04-02 04:09 UTC, ajibarra commented
Closing this since the code is outdated

2025-04-02 04:09 UTC, closed without merging