Feature/verbose error on registration
CakeDC/users pull request #957
Opened 2021-07-29 21:24 UTC by peter2796b

2021-07-30 14:15 UTC, rochamarcelo requested changes

2021-07-30 14:15 UTC, rochamarcelo commented on Docs/Documentation/Configuration.md
> +            'ShowVerboseError' => false,
Config should be in camelCase form, showVerboseError instead of ShowVerboseError

2021-07-30 14:15 UTC, rochamarcelo commented on config/users.php
> +            'ShowVerboseError' => false,
Config should be in camelCase form, showVerboseError instead of ShowVerboseError

2021-07-30 14:15 UTC, rochamarcelo commented on src/Controller/Traits/RegisterTrait.php
> +                $errors = \Collection($user->getErrors())->unfold()->toArray();
If no error messages show the default one

2021-07-30 14:15 UTC, rochamarcelo commented on src/Controller/Traits/RegisterTrait.php
> +            $errors = \Collection($user->getErrors())->unfold()->toArray();
If no error messages show the default one. 

Config should be in camelCase form, showVerboseError instead of ShowVerboseError

2021-07-30 14:18 UTC, rochamarcelo commented on src/Controller/Traits/RegisterTrait.php
> +                $errors = \Collection($user->getErrors())->unfold()->toArray();
use \collection  instead of \Collection

2021-08-02 11:09 UTC, steinkel commented
It looks good to me, please remember to merge it to 10.next-cake4 when done here

2021-08-05 14:32 UTC, rochamarcelo approved these changes

2021-09-29 17:49 UTC, merged